### ISSUE TITLE
Error checking OPML feed file

### ISSUE THREAD

**Issue by fmcpherson** [scripting/checkFeedsInOpml#1]
I thought this would be useful to check my RSS feed OPML file at http://writing.frankmcpherson.org/myOutlines/rssSubscriptions.opml 

I cloned this repo, and ran npm install

I edited check.jst to provide the above URL and then ran check.js

It starts to read my feeds and list with a "status code" of 200 and then generates the error below. The console output is not in the order of the OMPL file so I can't figure out what is the offending entry in the OPML. Is there a way to determine the order of the feeds being checked?

/home/frankmcpherson/projects/checkFeedsInOpml/check.js:36
                console.log (jstruct.text + ": " + response.statusCode);
                                                            ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/home/frankmcpherson/projects/checkFeedsInOpml/check.js:36:47)
    at self.callback (/home/frankmcpherson/projects/checkFeedsInOpml/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (/home/frankmcpherson/projects/checkFeedsInOpml/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by scripting** [comment]
I added a bit of error checking in check.js so it will report the error instead of getting a runtime error.

You'll be able to clearly see which feed is not being read.
